/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package stockanalysis;

/**
 *
 * @author rodrigoa
 */
public class SelectStockExchangePanel extends javax.swing.JPanel {

    private Controller controller;

    /**
     * Creates new form SelectStockExchangePanel
     */
    public SelectStockExchangePanel() {
        initComponents();
    }

    public void setController(Controller control) {
        this.controller = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        stockExchangeSelectDropBox = new javax.swing.JComboBox();
        continueButton = new javax.swing.JButton();

        jLabel1.setText("Select Stock Exchange");

        stockExchangeSelectDropBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NASDAQ", "NYSE", "LON", "ASX", "Stock Indexes" }));

        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 272, Short.MAX_VALUE))
                    .addComponent(stockExchangeSelectDropBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(continueButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockExchangeSelectDropBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(continueButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        int selectedStockExchange = this.stockExchangeSelectDropBox.getSelectedIndex();
        StockExchangeEnum stockExchangeEnum = StockExchangeEnum.NASDAQ;
        switch (selectedStockExchange) {
            case 0:
                stockExchangeEnum = StockExchangeEnum.NASDAQ;
                break;
            case 1:
                stockExchangeEnum = StockExchangeEnum.NYSE;
                break;
            case 2:
                stockExchangeEnum = StockExchangeEnum.LON;
                break;
            case 3:
                stockExchangeEnum = StockExchangeEnum.SWX;
                break;
            case 4:
                stockExchangeEnum = StockExchangeEnum.INDEXES;
                break;
        }

        this.controller.connectToDB();
        this.controller.setStockExchange(stockExchangeEnum);
    }//GEN-LAST:event_continueButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox stockExchangeSelectDropBox;
    // End of variables declaration//GEN-END:variables
}
